### PR TITLE
color changes, icon update

### PR DESCRIPTION
**Pull request by sathviknallamalli**
pull request to merge changes to the front end of the site into master. changes include color pallette change and icon logo

### CODE REVIEW

**Review by iristfu — APPROVED** [review]

**Comment by marcopizarro** [comment]
Good work! The only think I would edit is changing the logo and favicon to the three leaf symbol (found [here](https://www.figma.com/file/xXDZhD0y8ApNsPpTfJwdKT/2022-Branding?node-id=713%3A280)). Thanks!

**Comment by sathviknallamalli** [comment]
gotcha @marcopizarro , Ill make those changes (by tonight) and push them for a final review from you guys before deploying

**Comment by sathviknallamalli** [comment]
@marcopizarro , just made those changes and pushed to the branch

**Comment by marcopizarro** [comment]
Link to deployed: https://live-site-frontendupdat-mskgqa.herokuapp.com/. Sending this to Emily for final approval.

**Review by marcopizarro — APPROVED** [review]
Everything looks great! Thanks @sathviknallamalli!

**Pull request merged**
